import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { Flex, Stack, Box, Input, Heading, Grid, GridItem, Button, keyframes, SimpleGrid } from '@chakra-ui/react'


const ButtonNumber = ({ number, setLastNumber }) => {
    const [isActive, setisActive] = useState(false)

    return <Button
        variant={!isActive ? "outline" : "solid"}
        // colorScheme='green'
        colorScheme={isActive && 'green'}
        onClick={() => {
            setLastNumber(number);
            setisActive(!isActive);
        }}
    >
        {number}
    </Button >
}

const spin = keyframes`
  0% {
    transform: rotate(0deg);
    margin-left:1000%;
  }
  50% {
    transform: rotate(360deg)
  }
  100% {
    transform: rotate(720deg)
  }
`;

export default function Bingo() {
    const [lastNumber, setLastNumber] = useState(undefined)
    const numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8];
    const numbers2 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    const spinAnimation = `${spin} 2s linear`;
    const [selectedNumber, setSelectedNumber] = useState([])
    const selectNew = (number) => {
        const index = selectedNumber.indexOf(number);
        if (index > -1) {
            const copy = selectedNumber;
            copy.splice(index, 1);
            setSelectedNumber(copy)
        }
        else {
            setLastNumber(number)
            setSelectedNumber([...selectedNumber, number])
        }
    }

    return (
        <>
            <Head>
                <title>Bingo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Heading fontSize={80} textAlign="center">Bingo</Heading>
            <Box p={5}>
                <Flex
                    w="full"
                    direction={{ base: "column", lg: "row" }}
                    align="center"
                    justifyContent="space-between"
                >
                    <Stack mr={4} w="60vw">
                        <Heading fontSize="30vw" textAlign="center">{lastNumber || "😃"}</Heading>
                        {!lastNumber && <Heading textAlign="center">EMPEZAMOOOOS!!!!!</Heading>}
                    </Stack>
                    <Flex w="full" justifyContent="end" >
                        <Stack direction="row" h="full" w="full" justify="center">
                            {numbers.map(el => (
                                <Stack direction="column" key="el">
                                    {numbers2.map(el2 => (
                                        <ButtonNumber key={el2} number={el * 10 + el2} setLastNumber={selectNew} />
                                    ))}
                                </Stack>
                            ))}
                            <ButtonNumber number={90} setLastNumber={selectNew} />
                        </Stack>
                    </Flex>

                </Flex>
                <SimpleGrid columns={{ base: 10, md: 20 }} spacing={2} pt={10}>
                    {selectedNumber.map((el => (
                        <Flex
                            key={el}
                            align="center"
                            justify="center"
                            border="2px white solid"
                            borderRadius={"50%"}
                            w="30px"
                            h="30px"
                            animation={spinAnimation}
                            bg="white"
                            color="black" fontWeight={800}
                        >
                            {el}
                        </Flex>
                    )))}

                </SimpleGrid>
            </Box>
        </>
    )
}
